### ISSUE TITLE
latest version for 1.20.1 won't run because it now requires java 21

### ISSUE THREAD

**Issue by neptunecentury** [NemoNotFound/NemosBloomingBlossom#1]
Hi, I downloaded the latest version for Minecraft 1.20.1, but now it won't load because it requires Java 21. My Minecraft 1.20.1 instance runs on Java 17. Would you please correct this so that it will load with the default Java version for Minecraft 1.20.1?

Mod version: 1.3 - 1.20.1

For now, I have rolled back to version 1.20

Thanks!

**Comment by NemoNotFound** [comment]
Sure, will do it later!

**Comment by NemoNotFound** [comment]
It's currently uploading. Check out v1.3.0.1 and let me know if it works for you now

**Comment by neptunecentury** [comment]
I downloaded the 1.3.0.1 version, but it still requires Java 21
![image](https://github.com/user-attachments/assets/074f5d90-e619-49e7-8ae8-02cab4e8132c)

**Comment by NemoNotFound** [comment]
Ah damn, I set the version to 17 but forgot to change the fabric file, oops. Will fix that immediately :D

**Comment by NemoNotFound** [comment]
Okay, it's now uploading. 1.3.0.2 should fix it

**Comment by neptunecentury** [comment]
Yep, it works now! Thanks!

**Comment by NemoNotFound** [comment]
Great, hope you'll like the mod!
